workflows:
  ios:
    name: Build iOS
    max_build_duration: 60
    scripts:
      - name: Install Dependencies
        script: |
          gem install cocoapods --pre
          pod repo update
          pod install --repo-update
          flutter pub get
          flutter clean
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.ipa
