version: 2.0

pipelines:
  default:
    steps:
      - checkout

      - flutter-install:
          version: stable

      - run:
          name: Install CocoaPods
          command: |
            sudo gem install cocoapods
            pod repo update

      - run:
          name: Install Dependencies
          command: |
            cd ios
            pod install --repo-update

      - flutter-test

      - flutter-build:
          ios:
            build_mode: release

      - deploy:
          artifacts:
            - build/ios/iphoneos/Runner.app
