name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  flutter_test:
    name: Run Flutter Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'  # Update to the desired Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Project
        run: flutter analyze

      - name: Run Tests
        run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'  # Update to the desired Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Clean
        run: flutter clean

      - name: Build iOS
        run: flutter build ios --release --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'  # Update to the desired Flutter version

      - name: Install Dependencies
        run: flutter pub get

      - name: Clean
        run: flutter clean

      - name: Build AppBundle
        run: flutter build appbundle
